---
name: Text-MediawikiFormat
version: v1.0
author: []
abstract: Translate Wiki markup into other text formats
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 1.14
  URI: ''
  URI::Escape: ''
  version: 0.74
build_requires:
  Test::More: 0.3
  Test::NoWarnings: 0
  Test::Warn: 0
recommends:
  HTML::Parser: ''
  HTML::Tagset: ''
provides:
  Text::MediawikiFormat:
    file: lib/Text/MediawikiFormat.pm
    version: v1.0
  Text::MediawikiFormat::Block:
    file: lib/Text/MediawikiFormat/Blocks.pm
  Text::MediawikiFormat::Blocks:
    file: lib/Text/MediawikiFormat/Blocks.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
